FacePalm/FacePalm/Models/FriendRequests.cs
namespace FacePalm.Models
{
    public class FriendRequest
    {

        public string FromUserId { get; set; }

        public string ToUserId { get; set; }
    }
}

FacePalm/FacePalm/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using static FacePalm.Enums.FacePalmEnums;

namespace FacePalm.Models
{
    public class User
    {
        [Key]
        public string UserId { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public DateTime BirthDate { get; set; }
        [Required]
        public string Education { get; set; }
        [Required]
        public GenderTypes Gender { get; set; }
        public string Job { get; set; }
        [Required]
        public RelationshipStatus RelationshipStatus { get; set; }
        [Required]
        public ProfilePrivacyTypes ProfilePrivacy { get; set; }
        [DisplayName("Upload File")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual ICollection<User> Friends { get; set; }
        public List<string> AlbumsIds { get; set; }
        public List<string> ConversationsIds { get; set; }
        public List<string> GroupsIds { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Chat Chat { get; set; }

    }

}

FacePalm/FacePalm/Controllers/ChatController.cs
using FacePalm.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacePalm.Controllers
{
    public class ChatController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Chat
        [Authorize(Roles="User,Administrator")]
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var user = db.Users.Find(currentUser);
            ViewBag.currentUser = currentUser;
            ViewBag.Friends = user.Friends;
            ViewBag.Conversations = user.Conversations;
            var chat = db.Chats.Find(user.Chat.ChatId);
            return View(chat);
        }
    }
}

FacePalm/FacePalm/Controllers/UserController.cs
using FacePalm.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FacePalm.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        private ApplicationDbContext _applicationDBContext = new ApplicationDbContext();
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            var users = from user in _applicationDBContext.Users
                        orderby user.FirstName
                        select user;
            ViewBag.Users = users;
            return View();
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        public ActionResult Show(string id)
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            User user = _applicationDBContext.Users.Find(id);
            var posts = _applicationDBContext.Posts.Where(p => p.UserId == id);
            var albums = _applicationDBContext.Albums.Where(a => a.UserId == id);
            var currentUserId = User.Identity.GetUserId();
            ViewBag.User = user;
            ViewBag.CurrentUser = currentUserId;
            ViewBag.Posts = posts.OrderByDescending(x => x.Date);
            ViewBag.Albums = albums;
            var friendshipStatus = _applicationDBContext.Friendship.Any(f => (f.FirstUserId == currentUserId && f.SecondUserId == id) || (f.FirstUserId == id && f.SecondUserId == currentUserId));
            if (friendshipStatus)
            {
                ViewBag.IsFriend = true;
            }
            else
            {
                ViewBag.IsFriend = false;
            }
            var anyFriendRequest = _applicationDBContext.FriendRequests.Any(r => r.FromUserId == id && r.ToUserId == currentUserId);
            if (anyFriendRequest)
            {
                var friendReqFromUserToMe = _applicationDBContext.FriendRequests.Where(r => r.FromUserId == id && r.ToUserId == currentUserId);
                if (friendReqFromUserToMe != null)
                {
                    ViewBag.FriendRequestStatus = true;
                }
            }
            else
            {
                ViewBag.FriendRequestStatus = false;
            }

            return View();
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        public ActionResult Edit(string id)
        {
            User user = _applicationDBContext.Users.Find(id);
            ViewBag.User = user;
            if (user.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {

                return View(user);
            }
            else
            {
                TempData["message"] = "You do not have the rights to modify!";
                ViewBag.message = TempData["message"].ToString();

                return View("Error");
            }
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        [HttpPut]
        public ActionResult Edit(string id, User requestUser)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    User user = _applicationDBContext.Users.Find(id);
                    ViewBag.User = user;
                    if (user.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
                    {
                        
                        if (TryUpdateModel(user))
                        {
                            if(requestUser.ImageFile!=null)
                            {
                                string fileName = Path.GetFileNameWithoutExtension(requestUser.ImageFile.FileName);
                                string extension = Path.GetExtension(requestUser.ImageFile.FileName);
                                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                                user.ImagePath = "~/Images/" + fileName;
                                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                                user.ImageFile.SaveAs(fileName);
                            }
                            if (!String.IsNullOrEmpty(requestUser.FirstName))
                            {
                                user.FirstName = requestUser.FirstName;
                            }
                            if (!String.IsNullOrEmpty(requestUser.LastName))
                            {
                                user.LastName = requestUser.LastName;
                            }
                            if (!String.IsNullOrEmpty(requestUser.BirthDate.ToString()))
                            {
                                user.BirthDate = requestUser.BirthDate;
                            }
                            if (!String.IsNullOrEmpty(requestUser.Education))
                            {
                                user.Education = requestUser.Education;
                            }
                            if (!String.IsNullOrEmpty(requestUser.Job))
                            {
                                user.Job = requestUser.Job;
                            }
                            user.ProfilePrivacy = requestUser.ProfilePrivacy;
                            user.RelationshipStatus = requestUser.RelationshipStatus;
                            user.Gender = requestUser.Gender;
                            //user.ProfilePicture = requestUser.ProfilePicture;
                            _applicationDBContext.SaveChanges();
                        }
                        return RedirectToAction("Show/" + user.UserId);
                    }
                    else
                    {
                        TempData["message"] = "You do not have the rights to modify!";
                        ViewBag.message = TempData["message"].ToString();

                        return View("Error");
                    }
                }
                else
                {
                    TempData["message"] = "Something went wrong...";
                    ViewBag.message = TempData["message"].ToString();
                    return View("Error");
                }

            }
            catch (Exception ex)
            {
                TempData["message"] = "Something went wrong..." + ex.ToString();
                ViewBag.message = TempData["message"].ToString();
                return View("Error");
            }
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        [HttpDelete]
        public async Task<ActionResult> Delete(string id)
        {
            User user = _applicationDBContext.Users.Find(id);
            if (user.UserId == User.Identity.GetUserId() || User.IsInRole("Administrator"))
            {
                /*
                var albums = _applicationDBContext.Albums.Select(a => a.UserId == user.UserId);
                _applicationDBContext.Albums.Remove(albums);
                Comment comments = _applicationDBContext.Comments.FirstOrDefault(c => c.UserId == user.UserId);
                _applicationDBContext.Comments.Remove(comments);
                _applicationDBContext.Groups.Where(g => g.UsersIds.Remove(user.UserId));
                Conversation
                _applicationDBContext.Conversations.Remove
                */

                if (id == null)
                {
                    return View("Error");
                }

                _applicationDBContext.Users.Remove(user);
                _applicationDBContext.SaveChanges();
                TempData["message"] = "The user has been successfully removed!";
                ViewBag.message = TempData["message"].ToString();
                /*
                var _user = await UserManager.FindByIdAsync(id);

                //List Logins associated with user
                var logins = _user.Logins;

                //Gets list of Roles associated with current user
                var rolesForUser = await UserManager.GetRolesAsync(id);

                using (var transaction = context.Database.BeginTransaction())
                {
                    foreach (var login in logins.ToList())
                    {
                        await UserManager.RemoveLoginAsync(login.UserId, new UserLoginInfo(login.LoginProvider, login.ProviderKey));
                    }

                    if (rolesForUser.Count() > 0)
                    {
                        foreach (var item in rolesForUser.ToList())
                        {
                            // item should be the name of the role
                            var result = await UserManager.RemoveFromRoleAsync(_user.Id, item);
                        }
                    }

                    //Delete User
                    await UserManager.DeleteAsync(user);
                }
                */
                return View("../Home/Index");
            }
            else
            {
                TempData["message"] = "You do not have permission to delete this profile!";
                ViewBag.message = TempData["message"].ToString();
                return View("Error");
            }
        }

        public ActionResult Friends(string id)
        {
            try
            {
                var user = _applicationDBContext.Users.Find(id);
                ViewBag.Friends = user.Friends;
                return View();
            }
            catch (Exception ex)
            {
                TempData["message"] = "Something went wrong..." + ex.ToString();
                ViewBag.message = TempData["message"].ToString();
                return View("Error");
            }
        }




        [HttpPost]
        public ActionResult AddFriend(FriendRequest friendRequestData)
        {
            if (friendRequestData != null)
            {

FacePalm/FacePalm/Views/User/Edit.cshtml
@using FacePalm.Enums
@model FacePalm.Models.User
@{
    ViewBag.Title = "Edit";
}
<h2>Edit my profile</h2>

<form method="post" action="/User/Edit/@Model.UserId" enctype="multipart/form-data">
    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" />
        </div>
    </div>

    @Html.HttpMethodOverride(HttpVerbs.Put)
    <input type="hidden" name="Email" value="@Model.Email" />
    <input type="hidden" name="UserId" value="@Model.UserId" />
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.BirthDate, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Education, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Education, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Job, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Job, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Gender", "Gender")
        <div class="col-md-10">

            @Html.DropDownListFor(m => m.Gender, new SelectList(Enum.GetValues(typeof(FacePalmEnums.GenderTypes))), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("RelationshipStatus", "Relationship status")
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.RelationshipStatus, new SelectList(Enum.GetValues(typeof(FacePalmEnums.RelationshipStatus))), new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">

        @Html.Label("ProfilePrivacy", "Profile privacy")
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ProfilePrivacy, new SelectList(Enum.GetValues(typeof(FacePalmEnums.ProfilePrivacyTypes))), new { @class = "form-control" })
            </div>
        </div>
        <button class="btn btn-success" type="submit">Make changes</button>
</form>

<form method="post" action="/User/Delete/@ViewBag.User.UserId">
    @Html.HttpMethodOverride(HttpVerbs.Delete)
    <br/>
    <br/>
    <button class="btn btn-danger" type="submit"> Delete my account :( </button>
</form>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FacePalm/FacePalm/Views/User/FriendRequests.cshtml
<div class="container" style="opacity: 0.9;">
    @if(@ViewBag.FriendRequests == null)
    {
        <p>You don't have any friend requests at the moment. Have a nice day! :)</p>
    }
    else
    {
        <ul style="list-style:none">
            @foreach(FacePalm.Models.User fr in ViewBag.FriendRequests)
            {
            <li class="list-group-item">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div id="@fr.UserId" class="card">
                        <div class="card-body text-center text-capitalize">
                            @if (string.IsNullOrEmpty(fr.ImagePath))
                            {
                                <img class="rounded-circle img-fluid" style="width: 80px; height: 80px; border:1px solid 	#78C1AD" src="~/Images/profilePictureDefault.png" />
                            }
                            else
                            {
                                <img class="rounded-circle img-fluid" style="width: 80px; height: 80px; border:1px solid 	#78C1AD" src="@Url.Content(fr.ImagePath)">
                            }
                            <p class="card-title">@Html.ActionLink(fr.FirstName + " " + fr.LastName, "Show", "User", new { @id = fr.UserId }, null)</p>
                        </div>
                        <button class="acceptFriendRequest btn btn-success" title="" data-original-title="Accept">Accept</button>
                        <button class="declineFriendRequest btn btn-danger" title="" data-original-title="Decline">Decline</button>
                    </div><!-- /col-sm-12 -->
                </div>
               
            </li>
            }

        </ul>
    }
</div>

<script type="text/javascript">

   $(document).ready(function() {
       $(".acceptFriendRequest").click(function(event) {
           event.stopPropagation();
           event.stopImmediatePropagation();

           var friendRequestData = {
               FromUserId: $(this).parent().attr('id'),
               ToUserId: '@ViewBag.CurrentUser'
           };
           var buttonToHide = $(this);
           var nextButtonToHide = buttonToHide.next();
           $.ajax({
               type: 'POST',
               dataType: 'json',
               data: JSON.stringify({ "friendRequestData": friendRequestData }),
               url: '/User/AcceptFriendRequest',
               cache: false,
               contentType: 'application/json; charset=utf-8',
               success: function (serverAnswer) {
                   if (serverAnswer.success) {
                       //do something, remove button, add label "Friend request already sent"

                       buttonToHide.hide();
                       nextButtonToHide.hide();
                       
                   }
                   else
                   {
                       alert("The request couldn't be processed, please try again :(")
                   }
               },
               error: function () {
                   alert("There is something bad.");
               }
           });

        });
    });

    $(document).ready(function() {
       $(".declineFriendRequest").click(function(event) {
           event.stopPropagation();
           event.stopImmediatePropagation();
           $.ajax({
               type: 'POST',
               dataType: 'json',
               cache: false,
               contentType: 'application/json; charset=utf-8',
               success: function (serverAnswer) {
                   if (serverAnswer.success) {
                       $(this).hide();
                       $(this).prev().hide();
                   }
                   else
                   {
                       alert("The request couldn't be processed, please try again :(")
                   }
               },
               error: function () {
                   alert("error");
               }
           });

        });
    });

</script>

FacePalm/FacePalm/Views/User/Friends.cshtml
<div>
    @if (ViewBag.Friends.Count > 0)
    {
        <ul style="list-style:none">
            @foreach (var friend in @ViewBag.Friends)
            {
                <li>
                    @if (string.IsNullOrEmpty(friend.ImagePath))
                    {
                        <img src="~/Images/profilePictureDefault.png" />
                    }
                    else
                    {
                        <img src="@Url.Content(friend.ImagePath)" class="img-thumbnail img-profile">
                    }
                    <h3>@friend.FirstName @friend.LastName </h3>
                    <button class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="See profile"><span class="glyphicon glyphicon-envelope glyphicon glyphicon-white"></span><a href="/User/Show/@friend.UserId"> See profile</a></button>
                </li>
            }
        </ul>
    }
    else
    {
        <div class="card mb-3">
            <h3 class="card-header">You don't have a friend at the moment.</h3>

            <img style="width:593px; height:593px; block;" src="~/Images/sadPalm2.jpg" alt="Card image">
            
        </div>
    }
</div>

FacePalm/FacePalm/Views/User/Index.cshtml
<h2>FacePalm's registered users</h2>
@foreach (var user in ViewBag.Users)
{
    <p>@user.FirstName @user.LastName</p>
    <p>Email: @user.Email</p>
    <p>Birthdate: @user.BirthDate</p>
    <p>Their profile is: @user.ProfilePrivacy</p>
    <a href="/User/Show/@user.UserId">User's profile</a>
    <br />
    <hr />
    <br />
}
<br />

FacePalm/FacePalm/Views/User/Show.cshtml
<div class="col-md-16" style="padding-top:22px;">
    <div class="clearfix">
        @if (TempData.ContainsKey("message"))
        {
            <h3 class="alert alert-info" role="alert">@ViewBag.message</h3>
        }
        <div class="user clearfix row">
            <div class="col-md-4 avatar">
                @if (!string.IsNullOrEmpty(ViewBag.User.ImagePath))
                {
                    <img src="~/Images/profilePictureDefault.png" />
                }
                else
                {
                    <img src="@Url.Content(ViewBag.User.ImagePath)" class="img-thumbnail img-profile">
                }
            </div>
            <div class="col-md-4 userInformations ">
                <h1><span class="glyphicon glyphicon-asterisk"></span>@ViewBag.User.FirstName @ViewBag.User.LastName</h1>
                @if (@ViewBag.User.ProfilePrivacy.ToString().ToLower() == "private" && @ViewBag.User.UserId != @ViewBag.CurrentUser && !ViewBag.IsFriend && !User.IsInRole("Administrator"))
                {
                    if (ViewBag.FriendRequestStatus)
                    {
                        <p id="friendStatusLabel">A request has been sent! :) Let's hope for the best!</p>
                    }
                    else
                    {
                        <p id="friendStatusLabel">The user's profile is private. You can send a friend request.</p>
                        <button style="color:black" id="sendFriendRequest" class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Add Friend"><span class="glyphicon glyphicon-plus glyphicon glyphicon-blackboard"></span>Add Friend</button>
                    }

                }
                else
                {
                    <hr class="my-4">

                    <p>Date of birth: @ViewBag.User.BirthDate.ToShortDateString()</p>
                    <p>Education: @ViewBag.User.Education</p>
                    if (!string.IsNullOrEmpty(@ViewBag.User.Job))
                    {
                        <p>Job: @ViewBag.User.Job</p>
                    }
                    <p>Relationship status: @ViewBag.User.RelationshipStatus</p>
                }

            </div>
            <div class="col-md-4 actions">
                <div class="btn-group">
                    @if ((@ViewBag.User.UserId != @ViewBag.CurrentUser && ViewBag.isFriend) || (User.IsInRole("Administrator") || @ViewBag.User.UserId == @ViewBag.CurrentUser))
                    {
                        <button class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Friends"><span class="glyphicon glyphicon-plus glyphicon glyphicon-white"><a href="/User/Friends/@ViewBag.User.UserId"> Friends</a></span></button>
                    }

                    @if (@ViewBag.User.UserId != @ViewBag.CurrentUser && ViewBag.isFriend)
                    {
                        @Html.Hidden("RedirectTo", Url.Action("Index", "Chat"))
                        <button style="color:black" id="sendMessage" class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Send message"><span class="glyphicon glyphicon-envelope glyphicon glyphicon-white">Send message</span></button>
                        <button style="color:black" id="@ViewBag.User.UserId" class=" deleteFriend btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Delete friend"><span class="glyphicon glyphicon-envelope glyphicon glyphicon-white"> Delete friend</span></button>
                    }
                    @if (User.IsInRole("Administrator") || @ViewBag.User.UserId == @ViewBag.CurrentUser)
                    {
                        <button class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="GetFriendRequests"><a href="/User/GetFriendRequests"> See friend requests</a></button>
                        <button class="btn btn-default btn-sm tip btn-responsive" title="" data-original-title="Edit my profile"><a href="/User/Edit/@ViewBag.User.UserId"> Edit my profile</a></button>
                        <form method="post" action="/User/Delete/@ViewBag.User.UserId">
                            @Html.HttpMethodOverride(HttpVerbs.Delete)
                            <button class="btn btn-danger btn-sm tip btn-responsive" type="submit">Delete my profile</button>
                        </form>
                    }
                </div>
            </div>

        </div>

        <div class="container" ">

            @if (@ViewBag.User.ProfilePrivacy.ToString().ToLower() == "public" || @ViewBag.User.UserId == @ViewBag.CurrentUser || ViewBag.IsFriend || User.IsInRole("Administrator"))
            {
                <div class="album py-5 bg-light">
                    <div class="container">
                        <h3>@ViewBag.User.FirstName's albums</h3>
                        <ul class="list-group">
                            @foreach (FacePalm.Models.Album al in ViewBag.Albums)
                            {
                                <span class="row-cols-lg-3"><li class="list-group-item"><a class="btn btn-link" href="/Album/Show/@al.AlbumId">@al.AlbumTitle</a></li></span>
                            }
                        </ul>


                        <div class="album py-5 bg-light">
                            @* TODO: @clementlarisa Should be displayed if current user is friends with user *@
                            <h3> @ViewBag.User.FirstName's posts</h3>
                            @if (@ViewBag.User.UserId == @ViewBag.CurrentUser)
                            {
                                <br />
                                <a class="btn btn-success" href="/Post/New">Create a post</a>
                                <br /><br />
                            }
                            <div class="container">
                                <div class="row">
                                    @foreach (FacePalm.Models.Post post in ViewBag.Posts)
                                    {

                                        @Html.Partial("PostInfo", post)
                                        <br />
                                        <br />
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
 </div>


<script type="text/javascript">

   $(document).ready(function() {
       $("#sendFriendRequest").click(function() {

           var friendRequestData = {
               FromUserId: '@ViewBag.CurrentUser',
               ToUserId: '@ViewBag.User.UserId',
           };
           $.ajax({
               type: 'POST',
               dataType: 'json',
               data: JSON.stringify({ "friendRequestData": friendRequestData }),
               url: '/User/AddFriend',
               cache: false,
               contentType: 'application/json; charset=utf-8',
               success: function (serverAnswer) {
                   if (serverAnswer.success) {
                       //do something, remove button, add label "Friend request already sent"
                       $("#sendFriendRequest").hide();
                       $("#friendStatusLabel").text("A request has been sent! :) Let's hope for the best!");
                   }
                   else
                   {
                       alert("The request couldn't be processed, please try again :(")
                   }
               },
               error: function () {
                   alert("error");
               }
           });

        });
    });

    $(document).ready(function () {
        $(".deleteFriend").click(function () {

        $.ajax({
            type: 'POST',
            dataType: 'json',
            data: JSON.stringify({ "friendId": $(this).attr('id')}),
            url: '/User/DeleteFriend',
            cache: false,
            contentType: 'application/json; charset=utf-8',
            success: function (serverAnswer) {
                if (serverAnswer.success) {
                    location.reload();
                }
                else {
                    alert("The request couldn't be processed, please try again :(")
                }
            },
            error: function () {
                alert("error");
            }
        });
        })
    });

    $(document).ready(function() {
       $("#sendMessage").click(function() {

           var requestData = {
               FromUserId: '@ViewBag.CurrentUser',
               ToUserId: '@ViewBag.User.UserId',
           };
           $.ajax({
               type: 'POST',
               dataType: 'json',
               data: JSON.stringify({ "requestData": requestData }),
               url: '/User/SendMessage',
               cache: false,
               contentType: 'application/json; charset=utf-8',
               success: function (serverAnswer) {
                   if (serverAnswer.success) {
                       var url = $("#RedirectTo").val();
                       location.href = url;
                   }
                   else
                   {
                       alert("The request couldn't be processed, please try again :(")
                   }
               },
               error: function () {
                   alert("error");
               }
           });

        });
    });
</script>