FacePalm/FacePalm/Controllers/ChatController.cs
using FacePalm.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacePalm.Controllers
{
    public class ChatController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Chat
        [Authorize(Roles="User,Administrator")]
        public ActionResult Index()
        {
            var currentUser = User.Identity.GetUserId();
            var user = db.Users.Find(currentUser);
            ViewBag.currentUser = currentUser;
            ViewBag.Friends = user.Friends;
            ViewBag.Conversations = user.Conversations;
            var chat = db.Chats.Find(user.Chat.ChatId);
            return View(chat);
        }
    }
}

FacePalm/FacePalm/Controllers/PostController.cs
using FacePalm.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace FacePalm.Controllers
{
    public class PostController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Post
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            ViewBag.currentUserId = User.Identity.GetUserId();
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            return View(db.Posts.ToList().OrderByDescending(x => x.Date));
        }

        [Authorize(Roles = "User,Editor,Administrator")]
        // GET: Post/Show/5
        public ActionResult Show(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.afisareButoane = false;
            var currentUserId = User.Identity.GetUserId();
            if (User.IsInRole("Editor") || User.IsInRole("Administrator") || (post.UserId == currentUserId))
            {
                ViewBag.afisareButoane = true;
            }
            var usersPost = db.Users.Find(post.UserId);
            if(usersPost.Friends.Count == 0)
            {
                ViewBag.isFriend = false;
            }
            else
            {
                ViewBag.isFriend = (usersPost.Friends.FirstOrDefault(fr => fr.UserId == currentUserId) != null) ? true : false;

            }
            ViewBag.esteAdmin = User.IsInRole("Administrator");
            ViewBag.CurrentUser = currentUserId;
            ViewBag.numeCreator = db.Users.Find(post.UserId).FirstName;
            return View(post);
        }

        // GET: Post/New
        [HttpGet]
        public ActionResult New()
        {
            Post post = new Post();
            post.Albums = GetAllAlbums();

            post.UserId = User.Identity.GetUserId();

            return View(post);
        }

        // POST: Post/New
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult New(Post post)
        {
            try
            {
                if (post.ImageFile != null && post.AlbumId == null)
                {
                    throw new System.ArgumentException("You must choose an album!");
                }
                else
                {
                    if (post.ImageFile != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(post.ImageFile.FileName);
                        string extension = Path.GetExtension(post.ImageFile.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        post.ImagePath = "~/Images/" + fileName;
                        fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                        post.ImageFile.SaveAs(fileName);
                        post.Albums = GetAllAlbums();
                    }
                }
                if (ModelState.IsValid)
                {
                    db.Posts.Add(post);
                    db.SaveChanges();
                    ModelState.Clear();
                    return RedirectToAction("../User/Show/" + post.UserId);
                }
            }
            catch(Exception ex)
            {
                TempData["message"] = $"There has been a problem: /n {ex.ToString()}";
                ViewBag.message = TempData["message"].ToString();
                return View("../User/Error");
            }

            return View(post);
        }
        
        [HttpDelete]
        [Authorize(Roles = "User, Editor,Administrator")]
        // GET: Post/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                foreach (Comment com in post.Comments.ToList())
                {
                    db.Comments.Remove(com);
                }
                db.Posts.Remove(post);
                db.SaveChanges();
                TempData["message"] = "Post has been successfully deleted!";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                TempData["message"] = $"Something bad happened. {ex.ToString()}";
                ViewBag.message = TempData["message"].ToString();

                return View("Show");
            }
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllAlbums()
        {
            // generam o lista goala
            var selectList = new List<SelectListItem>();
            var userId = User.Identity.GetUserId();
            // Extragem toate albumele create de utilizator
            var albums = from al in db.Albums
                         where al.UserId == userId
                         select al;

            // iteram prin albume
            foreach (var album in albums)
            {
                // Adaugam in lista elementele necesare pentru dropdown
                selectList.Add(new SelectListItem
                {
                    Value = album.AlbumId.ToString(),
                    Text = album.AlbumTitle.ToString()
                });
            }

            // returnam lista de albume
            return selectList;
        }
    }
}

FacePalm/FacePalm/Views/Shared/CommentInfo.cshtml
@model FacePalm.Models.Comment

<div class="list-group-item list-group-item-action" style="background-color:aliceblue">
<div class="row media" style="justify-content:space-between">
    <div class="media-left">
        @if (string.IsNullOrEmpty(Model.User.ImagePath))
        {
            <img src="~/Images/profilePictureDefault.png" class="rounded-circle img-responsive" style="width: 60px; height: 60px; border:1px solid 	#78C1AD" />
        }
        else
        {
            <img src="@Url.Content(Model.User.ImagePath)" class="rounded-circle img-responsive" style="width: 60px; height: 60px; border:1px solid 	#78C1AD">
        }
    </div>
    <div class="media-body">
        <h5 class="media-heading"><a href="/User/Show/@Model.User.UserId">@Model.User.FirstName @Model.User.LastName</a></h5>
        <p class="text-muted" style="font-size:0.7rem">on @Html.DisplayFor(model => model.Date)</p>
    </div>
</div><!-- /col-sm-12 -->
<div class="row" style="justify-content:flex-start; align-content:flex-start">
    <div style="align-self: auto; flex-grow:1">
        @Html.DisplayFor(model => model.Content)
    </div><!-- /panel panel-default -->
    @if ((Model.UserId == ViewBag.CurrentUser) || User.IsInRole("Administrator"))
    {
        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="/Comment/Edit/@Html.DisplayFor(model => model.CommentId)"> Edit</a></button>

        <button type="button" class=" deleteComment btn btn-sm btn-outline-secondary"> Delete</button>
    }
</div>
    </div>
    <script>

    $(document).ready(function () {
        $(".deleteComment").click(function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                data: JSON.stringify({ "commentId": @Model.CommentId}),
                url: '/Comment/Delete/@Model.CommentId',
                cache: false,
                contentType: 'application/json; charset=utf-8',
                success: function (serverAnswer) {
                    if (serverAnswer.success) {
                        alert("Comment deleted successfully!");
                        location.reload();
                    }
                    else {
                        alert("The request couldn't be processed, please try again :(")
                    }
                },
                error: function () {
                    alert("error");
                }
            });
        })
    });
    </script>

FacePalm/FacePalm/Views/Shared/ConversationInfo.cshtml
@foreach (var conversation in @ViewBag.Conversations)
{
    <div id="@conversation.ConversationId" class="chat_list">
        <div class="chat_people">
            <div class="chat_img"> <img src="~/Images/palmBackground.png" alt="image"> </div>
            <div class="chat_ib">
                <h5>@conversation.Name</h5>
            </div>
        </div>
    </div>
}

<script>

    var selectedConv = -1;
    $(document).ready(function () {

        window.setInterval(function () {
            updater();
        }, 2000);

        $(".chat_list").click(function () {
            $(this).addClass("active_chat");
            var id = $(this).attr("id");

            if (selectedConv != -1)
            {
                $("#" + selectedConv).removeClass("active_chat");
            }
            selectedConv = id;
            updater();
        });


        var updater = function () {
            if (selectedConv == -1)
                return;

            $.ajax({
                type: 'POST',
                dataType: 'json',
                data: JSON.stringify({ "id": selectedConv}),
                url: '/Conversation/GetConversation',
                cache: false,
                contentType: 'application/json; charset=utf-8',
                success: function (serverAnswer) {
                    if (serverAnswer.success) {

                        $("#mesajeConversatie").empty();
                        var messages = jQuery.parseJSON(serverAnswer.conv);
                        for (var i = 0, l = messages.length; i < l; i++) {
                            var message = messages[i];

                            var direction = "left";
                            if (message.uid === '@ViewBag.currentUser')
                                direction = "right";
                            var html = "<div style=\"clear:both;float:" + direction + "\"class=\"sent_msg\"> <span class=\"time_date\">" + message.autor + "</span> <p>" + message.text + "</p> <span class=\"time_date\">" + message.date + "</span> </div>";
                            $("#mesajeConversatie").append(html);
                        }

                    }
                    else {
                        alert(serverAnswer.message);
                    }
                },
                error: function () {
                    alert("error");
                }
            });
        }
    });
</script>

FacePalm/FacePalm/Views/Shared/MessageInfo.cshtml
@model FacePalm.Models.Message

<div>
    <p>@Model.User.FirstName @Model.User.LastName</p>
    <p>@Html.DisplayFor(m => m.Date)</p>
    <div>
        @Html.DisplayFor(m => m.Content)
    </div>
</div>
<div class="msg_history">
    <div class="incoming_msg">
        <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        <div class="received_msg">
            <div class="received_withd_msg">
                <p>
                    Test which is a new approach to have all
                    solutions
                </p>
                <span class="time_date"> 11:01 AM    |    June 9</span>
            </div>
        </div>
    </div>
    <div class="outgoing_msg">
        <div class="sent_msg">
            <p>
                Test which is a new approach to have all
                solutions
            </p>
            <span class="time_date"> 11:01 AM    |    June 9</span>
        </div>
    </div>
    <div class="incoming_msg">
        <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        <div class="received_msg">
            <div class="received_withd_msg">
                <p>Test, which is a new approach to have</p>
                <span class="time_date"> 11:01 AM    |    Yesterday</span>
            </div>
        </div>
    </div>
    <div class="outgoing_msg">
        <div class="sent_msg">
            <p>Apollo University, Delhi, India Test</p>
            <span class="time_date"> 11:01 AM    |    Today</span>
        </div>
    </div>
    <div class="incoming_msg">
        <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        <div class="received_msg">
            <div class="received_withd_msg">
                <p>
                    We work directly with our designers and suppliers,
                    and sell direct to you, which means quality, exclusive
                    products, at a price anyone can afford.
                </p>
                <span class="time_date"> 11:01 AM    |    Today</span>
            </div>
        </div>
    </div>
</div>
<div class="type_msg">
    <div class="input_msg_write">
        <input type="text" class="write_msg" placeholder="Type a message" />
        <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
    </div>
</div>

FacePalm/FacePalm/Views/Shared/PostInfo.cshtml
@{ICollection<FacePalm.Models.Comment> comments = Model.Comments.ToList();}
@model FacePalm.Models.Post
@using FacePalm.Models



<div class="col-md-6">
    @if (Model.ImagePath != null)
    {
        <div class="card mb-4 box-shadow">
            <img class="card-img-top img-responsive" src="@Url.Content(Model.ImagePath)" />
        </div>
    }
    <div>
        <p class="card-text"> @Html.DisplayFor(model => model.ImageDescription) </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <button type="button" class="btn btn-sm btn-info"><a style="color:white" href="/Post/Show/@Html.DisplayFor(model => model.PostId)">View</a></button>
                <button type="button" class="addComment btn btn-sm btn-info">Add Comment</button>
                @if (User.IsInRole("Administrator") || @ViewBag.CurrentUser == Model.UserId)
                {
                    <form method="post" action="/Post/Delete/@Model.PostId">
                        @Html.HttpMethodOverride(HttpVerbs.Delete)
                        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                    </form>

                }
            </div>
            <small class="text-muted">on @Html.DisplayFor(model => model.Date)</small>
            <!--here comes the text area-->
        </div>

        <div>
            @if (comments.Count > 0)
            {
                if (comments.Count >= 3)
                {
                    var commsToDisplay = new List<Comment>();
                    commsToDisplay.Add(comments.ElementAt(comments.Count - 3));
                    commsToDisplay.Add(comments.ElementAt(comments.Count - 2));
                    commsToDisplay.Add(comments.ElementAt(comments.Count - 1));
                    foreach (var comm in commsToDisplay)
                    {
                        <div>
                            @Html.Partial("CommentInfo", comm)
                        </div>
                    }
                }
                else
                {
                    foreach (var comm in comments)
                    {
                        <div>
                            @Html.Partial("CommentInfo", comm)
                        </div>
                    }
                }
            }
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".addComment").click(function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            var textArea = $('<input display="inline-block" class="form-control" placeholder="Write a comment..." type="text">');
            $(this).parent().parent().parent().append(textArea);
            var $submitButton = $('<button type="button" class="submitCommentBtn btn btn-secondary">Add</button>');
            $submitButton.on('click', function (e) {
                var textAreaValue = $(this).parent().children().eq(3).val();
                var userId = '@ViewBag.CurrentUser';
                var comment = {
                    PostId: @Model.PostId,
                    UserId: userId,
                    Content: textAreaValue,
                    Date: new Date($.now())
                };
                var thisButton = $(this);
                var thisTextArea = $(this).parent().children().eq(3);
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    data: JSON.stringify({ "comment": comment }),
                    url: '/Comment/New',
                    cache: false,
                    contentType: 'application/json; charset=utf-8',
                    success: function (serverAnswer) {
                        if (serverAnswer.success) {
                            thisButton.remove();
                            thisTextArea.remove();
                            //Something to add the comm in the list
                            location.reload();
                        }
                        else {
                            alert("The request couldn't be processed, please try again :(")
                        }
                    },
                    error: function () {
                        alert("error");
                    }
                });
            });
            $(this).parent().parent().parent().append($submitButton);
            $(this).hide();
        });

    });

</script>

FacePalm/FacePalm/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
    <title>@ViewBag.Title - FacePalm Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="height:100%; background-image:url('../../Images/palmBackground4.png')">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">FacePalm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                {
                    <li class="nav-item">@Html.ActionLink("My Profile", "Show/" + User.Identity.GetUserId(), "User", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Account Settings", "Edit/" + User.Identity.GetUserId(), "User", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My Photo Albums", "Index/", "Album", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("My chat", "Index/", "Chat", null, new { @class = "nav-link" })</li>
                }
                @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                {
                    <li class="nav-item">@Html.ActionLink("All Users", "Index", "User", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("All Posts", "Index", "Post", null, new { @class = "nav-link" })</li>                }
            </ul>
            @using (Html.BeginForm("Search", "Search", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
            {
                @Html.TextBox("searchText", "", new{@class = "form-control mr-sm-2"})
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            }

            @Html.Partial("_LoginPartial")

        </div>
    </nav>
    <div class="container body-content" style="width:100%;">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - FacePalm Application</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>